#pragma once

#define dsyevd_ dsyevd
#define dsyev_ dsyev
#define dgemv_ dgemv
#define dgemm_ dgemm
#define ddot_ ddot
#define dsyrk_ dsyrk
#define dpotrf_ dpotrf
#define dgeqrf__ dgeqrf
#define dorgqr__ dorgqr
#define dpbtrf__ dpbtrf
#define dqeqrf__ dqeqrf
#define dgbsvx__ dgbsvx
#define dgbsvy__ dgbsvy
#define dgbcon__ dgbcon
#define dlansy__ dlansy
#define dpotrs__ dpotrs
#define dpocon__ dpocon
#define dsytrf__ dsytrf
#define dsycon__ dsycon
#define dposv__ dposv
#define dgels__ dgels
#define dgecon__ dgecon
#define dgbtrf__ dgbtrf
#define dgbtrs__ dgbtrs
#define dlange__ dlange
#define ilaenv__ ilaenv
#define dgelsd__ dgelsd
#define dtrtrs__ dtrtrs
#define dgesv__ dgesv
#define dtrcon__ dtrcon
#define dposvx__ dposvx
#define dgesvx__ dgesvx
#define dgetrf__ dgetrf
#define dgbsv__ dgbsv
#define dsytrs__ dsytrs
#define dgtsv__ dgtsv
#define dgvsv__ dgvsv
#define dgetrs__ dgetrs
