function applyThesisDefaults(style)
%APPLYTHESISDEFAULTS  Root defaults shared by thesis plotting scripts.
    if nargin < 1 || isempty(style)
        style = thesisPlotStyle();
    end

    set(groot, ...
        'defaultFigureColor', style.FigureColor, ...
        'defaultAxesFontName', style.FontName, ...
        'defaultTextFontName', style.FontName, ...
        'defaultLegendFontName', style.FontName, ...
        'defaultAxesFontSize', style.AxisFontSize, ...
        'defaultAxesLabelFontSizeMultiplier', style.LabelFontSize/style.AxisFontSize, ...
        'defaultAxesTitleFontSizeMultiplier', style.TitleFontSize/style.AxisFontSize, ...
        'defaultAxesLineWidth', style.AxisLineWidth, ...
        'defaultLineLineWidth', style.LineWidth, ...
        'defaultLineMarkerSize', style.MarkerSize, ...
        'defaultLegendFontSize', style.LegendFontSize, ...
        'defaultLegendBox', 'on', ...
        'defaultLegendColor', 'w', ...
        'defaultLegendEdgeColor', [0.35 0.35 0.35], ...
        'defaultAxesGridAlpha', style.GridAlpha, ...
        'defaultAxesMinorGridAlpha', style.MinorGridAlpha, ...
        'defaultAxesXGrid', 'on', ...
        'defaultAxesYGrid', 'on', ...
        'defaultAxesBox', 'on');
end
