function formatThesisFigure(fig, sizeKey, style)
%FORMATTHESISFIGURE  Apply shared size and text formatting before export.
    if nargin < 3 || isempty(style)
        style = thesisPlotStyle();
    end
    if nargin < 2 || isempty(sizeKey)
        sizeKey = 'single';
    end

    if isfield(style.FigureSize, sizeKey)
        fig_size = style.FigureSize.(sizeKey);
    else
        fig_size = style.FigureSize.single;
    end

    set(fig, ...
        'Color', style.FigureColor, ...
        'Units', 'centimeters', ...
        'Position', [2, 2, fig_size], ...
        'PaperUnits', 'centimeters', ...
        'PaperSize', fig_size, ...
        'PaperPosition', [0, 0, fig_size], ...
        'InvertHardcopy', 'off');

    ax = findall(fig, 'Type', 'axes');
    for i = 1:numel(ax)
        set(ax(i), ...
            'FontName', style.FontName, ...
            'FontSize', style.AxisFontSize, ...
            'LineWidth', style.AxisLineWidth, ...
            'GridAlpha', style.GridAlpha, ...
            'MinorGridAlpha', style.MinorGridAlpha, ...
            'Box', 'on');
        ax(i).XLabel.FontSize = style.LabelFontSize;
        ax(i).YLabel.FontSize = style.LabelFontSize;
        ax(i).Title.FontSize = style.TitleFontSize;
        ax(i).Title.FontWeight = 'bold';
    end

    leg = findall(fig, 'Type', 'legend');
    for i = 1:numel(leg)
        set(leg(i), ...
            'FontName', style.FontName, ...
            'FontSize', style.LegendFontSize, ...
            'Box', 'on', ...
            'Color', 'w', ...
            'EdgeColor', [0.35 0.35 0.35]);
    end
end
