%% workingSimulatorReducedOrderTiming.m
% =========================================================================
%  Timing-experiment variant of workingSimulatorReducedOrder.m.
%
%  Procedure:
%    1. Force-clean c_generated_code/ (cold compile).
%    2. Build OCP + sim solvers; record the wall-clock build time.
%    3. Run the simulation n_runs times in one MATLAB session, reusing the
%       in-memory solvers. Record per step:
%          - acados time_tot   (pure C-side solver work)
%          - wall-clock tic/toc around set('constr_x0') + solve + get('u',0)
%            (what the hardware loop will actually pay from MATLAB).
%    4. Save raw + aggregated timings + system metadata to a uniquely-named
%       .mat file so results from different OS / launch-flag combinations
%       can be copied together for comparison.
%
%  No plotting: plotting would skew wall-clock timings and is not part of
%  the experiment.
%
%  Author: Marius Jullum Faanes
%  Based on: workingSimulatorReducedOrder.m
% =========================================================================

%% --- AGGRESSIVE SESSION CLEANUP ---
% `clear classes` removes variables, MEX bindings, AND cached classdef
% definitions. The latter matters because the templated mex_solver class
% (e.g. maglev_nmpc_reduced_mex_solver) is regenerated by the cold compile
% below — without dropping the cached version, MATLAB can mix the old
% class definition with the new MEX, producing field-name errors during
% destruction at the end of the run.
% NOTE: this also clears n_runs / sim_steps / force_clean_build, so they
% are (re-)set after the clear.
clear classes; clc; %#ok<CLCLS>

%% --- EXPERIMENT PARAMETERS ---
n_runs            = 10;
sim_steps         = 1000;
force_clean_build = true;

%% --- PROJECT SETUP ---
if ispc
    acados_root  = 'C:\Users\mariujf\acados';
    project_root = 'C:\Users\mariujf\Maggy2026V\NMPCProject';
else
    acados_root  = '/home/mariujf/acados';
    project_root = '/home/mariujf/Maggy2026V/NMPCProject';
end

setenv('ACADOS_SOURCE_DIR',        acados_root);
setenv('ENV_ACADOS_INSTALL_DIR',   acados_root);
setenv('ACADOS_INSTALL_DIR',       acados_root);

addpath(fullfile(acados_root, 'interfaces', 'acados_matlab_octave'));
addpath(fullfile(acados_root, 'external',   'jsonlab'));
addpath(fullfile(acados_root, 'external',   'casadi-matlab'));

addpath(genpath(fullfile(project_root, 'model_implementations')));
addpath(genpath(fullfile(project_root, 'system_parameters')));
addpath(genpath(fullfile(project_root, 'utilities')));

import casadi.*

%% --- CLEAN BUILD ---
% Two folders must be removed for a true cold compile:
%   c_generated_code/  -> model-specific generated C, .dll/.so, mexw64/mexa64
%   build/             -> generic acados MEX wrappers (ocp_get, sim_solve, ...)
%                         The wrapper auto-detect (AcadosOcpSolver.m:728) keeps
%                         these if link_libs.json matches, so a stale wrapper
%                         from a previous acados version can survive a
%                         c_generated_code/ wipe and cause schema-mismatch
%                         errors. Delete it explicitly.
gen_dir   = fullfile(project_root, 'c_generated_code');
build_dir = fullfile(project_root, 'build');
if force_clean_build
    if exist(gen_dir, 'dir')
        fprintf('--- Removing %s ---\n', gen_dir);
        rmdir(gen_dir, 's');
    end
    if exist(build_dir, 'dir')
        fprintf('--- Removing %s ---\n', build_dir);
        rmdir(build_dir, 's');
    end
end

%% --- MODEL SETUP (reduced order: 10 states) ---
nx_full = 12;
nx      = 10;
nu      = 4;

x_full = SX.sym('x_full', nx_full);
u_sym  = SX.sym('u', nu);

parameters_maggy_V4;
correctionFactorFast       = computeSolenoidRadiusCorrectionFactor(params, 'fast');
paramsFast                 = params;
paramsFast.solenoids.r     = correctionFactorFast * paramsFast.solenoids.r;

%% --- BUILD FULL-ORDER CASADI FUNCTION (for equilibrium search) ---
f_expl_full = maglevSystemDynamicsCasADi(x_full, u_sym, paramsFast);
f_func_full = casadi.Function('f_full', {x_full, u_sym}, {f_expl_full});

%% --- FIND EQUILIBRIUM (using full model with gamma=0, wz=0) ---
fprintf('--- Searching for equilibrium z with u = 0 ---\n');

z_var    = SX.sym('z_eq');
u_zero   = zeros(nu, 1);
x_eq_sym = [0; 0; z_var; zeros(9,1)];
accel    = f_func_full(x_eq_sym, u_zero);
fz_residual = accel(9);

nlp       = struct('x', z_var, 'f', fz_residual^2);
solver_eq = nlpsol('solver_eq', 'ipopt', nlp, ...
    struct('ipopt', struct('print_level', 3)));

sol     = solver_eq('x0', 0.030, 'lbx', 0.015, 'ubx', 0.060);
zEq_cas = full(sol.x);
uEq     = zeros(nu, 1);

xEq = [0; 0; zEq_cas; zeros(7,1)];

fprintf('Equilibrium: z = %.6f m, u = [0, 0, 0, 0]\n', zEq_cas);

%% --- BUILD REDUCED-ORDER DYNAMICS ---
x_r    = SX.sym('x_r', nx);
xdot_r = SX.sym('xdot_r', nx);

x_full_from_r = [x_r(1:5); 0; x_r(6:8); x_r(9:10); 0];
dx_full       = f_func_full(x_full_from_r, u_sym);
f_expl_r      = [dx_full(1:5); dx_full(7:11)];

%% --- OCP SETUP ---
N      = 10;
Tf     = 0.1;
dt_mpc = Tf / N;

Q = diag([1e2, 1e2, 1e3, ...
          1e3, 1e3, ...
          1e1, 1e1, 1e1, ...
          1e1, 1e1]);
R = eye(nu) * 1.0;

ocp = AcadosOcp();
ocp.model.name        = 'maglev_nmpc_reduced';
ocp.model.x           = x_r;
ocp.model.u           = u_sym;
ocp.model.xdot        = xdot_r;
ocp.model.f_impl_expr = xdot_r - f_expl_r;

ocp.solver_options.N_horizon             = N;
ocp.solver_options.tf                    = Tf;
ocp.solver_options.integrator_type       = 'IRK';
ocp.solver_options.sim_method_num_stages = 2;
ocp.solver_options.sim_method_num_steps  = 5;
ocp.solver_options.nlp_solver_type       = 'SQP_RTI';
ocp.solver_options.nlp_solver_tol_stat   = 1e-4;
ocp.solver_options.nlp_solver_tol_eq     = 1e-4;
ocp.solver_options.nlp_solver_tol_ineq   = 1e-4;
ocp.solver_options.nlp_solver_tol_comp   = 1e-4;
ocp.solver_options.qp_solver             = 'PARTIAL_CONDENSING_HPIPM';
ocp.solver_options.qp_solver_iter_max    = 200;
ocp.solver_options.qp_solver_warm_start  = 1;
ocp.solver_options.hessian_approx        = 'GAUSS_NEWTON';
ocp.solver_options.regularize_method     = 'CONVEXIFY';

ocp.cost.cost_type   = 'NONLINEAR_LS';
ocp.cost.cost_type_0 = 'NONLINEAR_LS';
ocp.cost.cost_type_e = 'NONLINEAR_LS';
ocp.cost.W           = blkdiag(Q, R);
ocp.cost.W_0         = blkdiag(Q, R);
ocp.cost.W_e         = Q * 50;

ocp.model.cost_y_expr   = [x_r; u_sym];
ocp.model.cost_y_expr_0 = [x_r; u_sym];
ocp.model.cost_y_expr_e = x_r;

ocp.cost.yref   = [xEq; uEq];
ocp.cost.yref_0 = [xEq; uEq];
ocp.cost.yref_e = xEq;

ocp.constraints.idxbu = 0:nu-1;
ocp.constraints.lbu   = -1 * ones(nu,1);
ocp.constraints.ubu   =  1 * ones(nu,1);

ocp.constraints.idxbx  = [0, 1, 2, 3, 4];
ocp.constraints.lbx    = [-0.025; -0.025; 0.015; -0.35; -0.35];
ocp.constraints.ubx    = [ 0.025;  0.025; 0.055;  0.35;  0.35];
ocp.constraints.idxsbx = 0:4;

n_sbx = 5;
ocp.cost.Zl = 1e3 * ones(n_sbx, 1);
ocp.cost.Zu = 1e3 * ones(n_sbx, 1);
ocp.cost.zl = 1e2 * ones(n_sbx, 1);
ocp.cost.zu = 1e2 * ones(n_sbx, 1);

ocp.constraints.x0 = xEq;

%% --- TIMED COLD BUILD ---
fprintf('\n--- Cold build (acados OCP + sim solvers) ---\n');
t_compile = tic;

ocp_solver = AcadosOcpSolver(ocp);

sim = AcadosSim();
sim.model.name        = 'maglev_sim_reduced';
sim.model.x           = x_r;
sim.model.u           = u_sym;
sim.model.xdot        = xdot_r;
sim.model.f_impl_expr = xdot_r - f_expl_r;
sim.solver_options.Tsim            = dt_mpc;
sim.solver_options.integrator_type = 'IRK';
sim.solver_options.num_stages      = 4;
sim.solver_options.num_steps       = 10;
sim_solver = AcadosSimSolver(sim);

compile_time_s = toc(t_compile);
fprintf('Compile time: %.2f s\n', compile_time_s);

%% --- INITIAL CONDITION (same per run) ---
dx_dir = [0.005; -0.008; 0.010; 0.15; -0.10; ...
          0.01;  -0.01;  0.0;   0.2;  -0.3];

perturbation_scale = 0.05;
x_init = xEq + perturbation_scale * dx_dir;

dist_time      = 5.0;
dist_step      = round(dist_time / dt_mpc);
push_magnitude = [0; 0; 0; 0; 0; -0.005; 0.0025; -0.2; 0; 0];

%% --- ALLOCATE EXPERIMENT LOGS ---
solve_time_acados = zeros(n_runs, sim_steps);
solve_time_wall   = zeros(n_runs, sim_steps);
status_log        = zeros(n_runs, sim_steps);
sqp_iter_log      = zeros(n_runs, sim_steps);
n_actual_log      = zeros(1, n_runs);
diverged_log      = false(1, n_runs);

avg_solve_time_acados = zeros(1, n_runs);
max_solve_time_acados = zeros(1, n_runs);
avg_solve_time_wall   = zeros(1, n_runs);
max_solve_time_wall   = zeros(1, n_runs);

%% --- EXPERIMENT LOOP ---
fprintf('\n--- Running %d simulations of %d steps each ---\n', n_runs, sim_steps);

for r = 1:n_runs
    x_current = x_init;

    % Re-seed warm-start trajectory (same for every run)
    for k = 0:N
        alpha_k = k / N;
        ocp_solver.set('x', (1 - alpha_k) * x_current + alpha_k * xEq, k);
    end
    for k = 0:N-1
        ocp_solver.set('u', uEq, k);
    end

    n_actual = sim_steps;
    diverged = false;

    for i = 1:sim_steps
        % --- Timed: state-in to control-out (the hardware-deadline metric) ---
        t_step = tic;
        ocp_solver.set('constr_x0', x_current);
        ocp_solver.solve();
        u_applied = ocp_solver.get('u', 0);
        solve_time_wall(r, i)   = toc(t_step);
        solve_time_acados(r, i) = ocp_solver.get('time_tot');

        u_applied            = max(min(u_applied, 1), -1);
        status_log(r, i)     = ocp_solver.get('status');
        sqp_iter_log(r, i)   = ocp_solver.get('sqp_iter');

        % --- Plant step (NOT timed) ---
        sim_solver.set('x', x_current);
        sim_solver.set('u', u_applied);
        sim_solver.solve();
        x_next = sim_solver.get('xn');

        if i == dist_step
            x_next = x_next + push_magnitude;
        end

        % --- Warm-start shift (NOT timed) ---
        x_traj = ocp_solver.get('x');
        u_traj = ocp_solver.get('u');
        x_traj_shift = [x_traj(:, 2:end), xEq];
        u_traj_shift = [u_traj(:, 2:end), uEq];
        for k = 0:N
            ocp_solver.set('x', x_traj_shift(:, k+1), k);
        end
        for k = 0:N-1
            ocp_solver.set('u', u_traj_shift(:, k+1), k);
        end

        diverged = abs(x_next(3)) > 0.5 || max(abs(x_next(4:5))) > pi || ...
                   any(isnan(x_next)) || any(isinf(x_next));
        if diverged
            n_actual = i;
            break;
        end

        x_current = x_next;
    end

    n_actual_log(r) = n_actual;
    diverged_log(r) = diverged;

    avg_solve_time_acados(r) = mean(solve_time_acados(r, 1:n_actual));
    max_solve_time_acados(r) = max(solve_time_acados(r, 1:n_actual));
    avg_solve_time_wall(r)   = mean(solve_time_wall(r, 1:n_actual));
    max_solve_time_wall(r)   = max(solve_time_wall(r, 1:n_actual));

    fprintf(['Run %2d/%d: avg_acados=%5.2f ms  max_acados=%5.2f ms  ' ...
             'avg_wall=%5.2f ms  max_wall=%5.2f ms%s\n'], ...
        r, n_runs, ...
        avg_solve_time_acados(r)*1000, max_solve_time_acados(r)*1000, ...
        avg_solve_time_wall(r)*1000,   max_solve_time_wall(r)*1000, ...
        ternary(diverged, sprintf('  [DIVERGED at step %d]', n_actual), ''));
end

%% --- AGGREGATE STATISTICS ---
aggregate.mean_avg_acados = mean(avg_solve_time_acados);
aggregate.std_avg_acados  = std(avg_solve_time_acados);
aggregate.mean_max_acados = mean(max_solve_time_acados);
aggregate.std_max_acados  = std(max_solve_time_acados);

aggregate.mean_avg_wall = mean(avg_solve_time_wall);
aggregate.std_avg_wall  = std(avg_solve_time_wall);
aggregate.mean_max_wall = mean(max_solve_time_wall);
aggregate.std_max_wall  = std(max_solve_time_wall);

%% --- METADATA ---
meta.computer_arch  = computer('arch');
meta.matlab_release = version('-release');
meta.matlab_version = version();
meta.has_jvm        = usejava('jvm');
meta.has_desktop    = usejava('desktop');
meta.is_wsl         = ~isempty(getenv('WSL_DISTRO_NAME'));
meta.timestamp      = datetime('now');
meta.n_runs         = n_runs;
meta.sim_steps      = sim_steps;
meta.dt_mpc         = dt_mpc;
meta.N              = N;
meta.Tf             = Tf;
meta.nx             = nx;
meta.nu             = nu;

%% --- SAVE ---
per_run.solve_time_acados     = solve_time_acados;
per_run.solve_time_wall       = solve_time_wall;
per_run.status                = status_log;
per_run.sqp_iter              = sqp_iter_log;
per_run.avg_solve_time_acados = avg_solve_time_acados;
per_run.max_solve_time_acados = max_solve_time_acados;
per_run.avg_solve_time_wall   = avg_solve_time_wall;
per_run.max_solve_time_wall   = max_solve_time_wall;
per_run.n_actual              = n_actual_log;
per_run.diverged              = diverged_log;

ts    = datestr(now, 'yyyymmdd_HHMMSS');
fname = sprintf('timing_results_%s_R%s_%s.mat', ...
                meta.computer_arch, meta.matlab_release, ts);
save(fname, 'compile_time_s', 'per_run', 'aggregate', 'meta');

%% --- FINAL PRINTOUT ---
fprintf('\n=== Timing summary (compile + %d runs of %d steps) ===\n', n_runs, sim_steps);
fprintf('  Compile time:                %6.2f s\n', compile_time_s);
fprintf('  Avg solve time (acados):     %6.2f +/- %.2f ms\n', ...
    aggregate.mean_avg_acados*1000, aggregate.std_avg_acados*1000);
fprintf('  Max solve time (acados):     %6.2f +/- %.2f ms\n', ...
    aggregate.mean_max_acados*1000, aggregate.std_max_acados*1000);
fprintf('  Avg solve time (wall-clock): %6.2f +/- %.2f ms\n', ...
    aggregate.mean_avg_wall*1000, aggregate.std_avg_wall*1000);
fprintf('  Max solve time (wall-clock): %6.2f +/- %.2f ms\n', ...
    aggregate.mean_max_wall*1000, aggregate.std_max_wall*1000);
fprintf('  Saved to: %s\n', fname);
if any(diverged_log)
    fprintf('  WARNING: %d run(s) diverged\n', sum(diverged_log));
end

%% --- LOCAL HELPERS ---
function out = ternary(cond, a, b)
    if cond, out = a; else, out = b; end
end
